### Types of vectors

#### Column vector

In [1]:
import numpy as np

##### Example 1

In [2]:
# Example dataset: Student exam scores
math_scores    = np.array([85, 90, 78, 92])
physics_scores = np.array([70, 88, 75, 82])
history_scores = np.array([65, 75, 80, 72])

# Create column vectors
student1_scores = np.array([[math_scores[0]], [physics_scores[0]], [history_scores[0]]])
student2_scores = np.array([[math_scores[1]], [physics_scores[1]], [history_scores[1]]])

# print("Student 1 Scores:\n", student1_scores)
# print("Student 2 Scores:\n", student2_scores)

In [3]:
student1_scores

array([[85],
       [70],
       [65]])

In [4]:
student2_scores

array([[90],
       [88],
       [75]])

`student1_scores` and `student2_scores` are column vectors representing the exam scores of two different students.

##### Example 2: Representing Features

In machine learning, column vectors are often used to represent features. Let's consider a dataset of house characteristics, and we want to represent each house's features as a column vector.

In [5]:
# Example dataset: House features
house1_features = np.array([2000, 3, 2.5])  # [Square footage, Bedrooms, Bathrooms]
house2_features = np.array([1500, 2, 2.0])

In [6]:
# Create column vectors
house1_vector = house1_features.reshape(-1, 1)
house2_vector = house2_features.reshape(-1, 1)

In [7]:
house1_vector

array([[2000. ],
       [   3. ],
       [   2.5]])

In [8]:
house2_vector

array([[1500.],
       [   2.],
       [   2.]])

##### Application: Linear Regression

Column vectors are widely used in linear regression, where the features of each data point are represented as column vectors. These vectors are used to compute the predictions and perform optimization to find the best-fitting line or hyperplane.

In [9]:
from sklearn.linear_model import LinearRegression

In [10]:
# Example dataset: House features and prices
features = np.array([[2000, 3], 
                     [1500, 2]])  # Features: Square footage, Bedrooms
prices   = np.array([300000, 200000])  # Prices

In [11]:
# Create a linear regression model
model = LinearRegression()
model.fit(features, prices)

LinearRegression()

In [12]:
# Predict price for a new house
new_house = np.array([[1800, 2]])
predicted_price = model.predict(new_house)

print("Predicted Price:", predicted_price)

Predicted Price: [259999.76000096]


In this example, the feature vectors are used to train a linear regression model to predict house prices based on square footage and number of bedrooms. The prediction is then made using a new feature vector representing a new house's features.

#### Row Vector

Row vectors are horizontal vectors that consist of a single row of values. In data science and machine learning, row vectors are used to represent features, coefficients, or instances in various computations and analyses. 

In [13]:
# Example feature row vector (age, test score, hours studied)
student_features = np.array([20, 85, 10])

In [14]:
print("Feature Row Vector:", student_features)

Feature Row Vector: [20 85 10]


**Application: Calculating Dot Product**

- One common application of row vectors is calculating the dot product between two vectors. 

- The dot product measures the similarity between vectors and is used in various algorithms, including linear regression and neural networks.

In [15]:
# Example row vectors
vector1 = np.array([2, 3, 4])
vector2 = np.array([5, 1, 2])

In [16]:
# Calculate dot product
dot_product = np.dot(vector1, vector2)

print("Dot Product:", dot_product)

Dot Product: 21


To normalize the dot product, you can divide the dot product of two vectors by the product of their magnitudes. This normalization technique results in a value between -1 and 1, known as the cosine similarity.

In [17]:
# Calculate magnitudes of the vectors
magnitude1 = np.linalg.norm(vector1)
magnitude2 = np.linalg.norm(vector2)

# Calculate cosine similarity (normalized dot product)
cosine_similarity = dot_product / (magnitude1 * magnitude2)

print("Cosine Similarity:", cosine_similarity)

Cosine Similarity: 0.7119666788018509


#### Position vectors

- Position vectors describe the position of a point relative to a reference point or origin. 

- While they are not as commonly used in traditional data science and machine learning tasks, they can have applications in specialized areas like `geospatial analysis` and computer graphics. 

##### Example: Geospatial Analysis

Let's say you're working with geospatial data and want to calculate the distance between two points on the Earth's surface using their latitude and longitude coordinates. 

Position vectors can help represent the locations of these points.

In [18]:
# Coordinates of two points (latitude, longitude)
point_a = np.array([37.7749, -122.4194])  # San Francisco
point_b = np.array([34.0522, -118.2437])  # Los Angeles

In [19]:
# Calculate the distance using Haversine formula
def haversine_distance(coord1, coord2):
    R = 6371  # Radius of Earth in kilometers
    dlat = np.radians(coord2[0] - coord1[0])
    dlon = np.radians(coord2[1] - coord1[1])
    a = np.sin(dlat / 2) ** 2 + np.cos(np.radians(coord1[0])) * np.cos(np.radians(coord2[0])) * np.sin(dlon / 2) ** 2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))
    distance = R * c
    return distance

In [20]:
distance = haversine_distance(point_a, point_b)
print("Distance between San Francisco and Los Angeles:", distance, "km")

Distance between San Francisco and Los Angeles: 559.1205770615533 km
