---------------------
#### properties of vectors
------------------------

##### Commutative Property:

The commutative property states that the order of operands does not affect the result of an operation. 

For vector addition, this means that changing the order in which vectors are added does not change the sum.

v+w=w+v

In [2]:
import numpy as np

vector_v = np.array([3, 4])
vector_w = np.array([1, 2])

result1 = vector_v + vector_w
result2 = vector_w + vector_v

print("Result using v + w:", result1)
print("Result using w + v:", result2)

Result using v + w: [4 6]
Result using w + v: [4 6]


##### Additive Identity Property:
The additive identity property states that adding a zero vector to any vector does not change the vector.

v+0=v

In [3]:
vector_v    = np.array([3, 4])
zero_vector = np.array([0, 0])

result = vector_v + zero_vector

print("Result using v + 0:", result)

Result using v + 0: [3 4]


##### Associative Property:
The associative property states that the `grouping of vectors` in an operation does not affect the result. 

For vector addition, this means that the sum of three vectors is the same regardless of how you group them.


(u+v)+w=u+(v+w)

In [4]:
vector_u = np.array([1, 2])
vector_v = np.array([3, 4])
vector_w = np.array([5, 6])

result1 = (vector_u + vector_v) + vector_w
result2 = vector_u + (vector_v + vector_w)

print("Result using (u + v) + w:", result1)
print("Result using u + (v + w):", result2)

Result using (u + v) + w: [ 9 12]
Result using u + (v + w): [ 9 12]


#### python code taking examples from DS/ML

##### Commutative Property: Euclidean Distance Calculation

In [5]:
import numpy as np
from scipy.spatial.distance import euclidean

In [6]:
# Example data points
data_point1 = np.array([3, 4, 5])
data_point2 = np.array([1, 2, 3])

In [7]:
distance1 = euclidean(data_point1, data_point2)
distance2 = euclidean(data_point2, data_point1)

In [8]:
print("Distance between data_point1 and data_point2:", distance1)
print("Distance between data_point2 and data_point1:", distance2)

Distance between data_point1 and data_point2: 3.4641016151377544
Distance between data_point2 and data_point1: 3.4641016151377544


##### Associative Property: PCA Dimension Reduction

In [9]:
from sklearn.decomposition import PCA

In [10]:
# Example dataset (samples in rows, features in columns)
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

In [11]:
# Applying PCA: (u + v) + w vs. u + (v + w)
pca1 = PCA(n_components=2)
result1 = pca1.fit_transform(data)

In [12]:
pca2 = PCA(n_components=2)
result2 = pca2.fit_transform(pca1.transform(data))

In [13]:
print("Result using (u + v) + w:\n", result1)
print("Result using u + (v + w):\n", result2)

Result using (u + v) + w:
 [[-5.19615242e+00  3.62353582e-16]
 [ 0.00000000e+00  0.00000000e+00]
 [ 5.19615242e+00  3.62353582e-16]]
Result using u + (v + w):
 [[-5.19615242e+00  1.60219646e-31]
 [ 0.00000000e+00  0.00000000e+00]
 [ 5.19615242e+00  1.60219646e-31]]


##### Associative Property: Feature Engineering

In [14]:
from sklearn.preprocessing import MinMaxScaler

In [15]:
# Example dataset (samples in rows, features in columns)
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

In [16]:
# Applying feature scaling: (u + v) + w vs. u + (v + w)
scaler1 = MinMaxScaler()
result1 = scaler1.fit_transform(data)

In [19]:
result1

array([[0. , 0. , 0. ],
       [0.5, 0.5, 0.5],
       [1. , 1. , 1. ]])

In [17]:
scaler2 = MinMaxScaler()
result2 = scaler2.fit_transform(scaler1.transform(data))

In [18]:
print("Result using (u + v) + w:\n", result1)
print("Result using u + (v + w):\n", result2)

Result using (u + v) + w:
 [[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]
Result using u + (v + w):
 [[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]


##### Distributive Property over Vector Addition:
Scalar multiplication distributes over vector addition. This property states that multiplying a scalar by the sum of two vectors is the same as the sum of the scalar multiples of those vectors.

c⋅(u+v)=c⋅u+c⋅v

In [21]:
scalar = 2
vector_u = np.array([1, 2])
vector_v = np.array([3, 4])

result1 = scalar * (vector_u + vector_v)
result2 = scalar *  vector_u + scalar * vector_v

print("Result using c * (u + v):", result1)
print("Result using c * u + c * v:", result2)

Result using c * (u + v): [ 8 12]
Result using c * u + c * v: [ 8 12]


##### Associative Property of Scalar Multiplication:
Scalar multiplication is associative, meaning that the product of a scalar and the product of two vectors is the same, regardless of how you group the scalars and vectors.


(a⋅b)⋅v=a⋅(b⋅v)

In [22]:
scalar_a = 2
scalar_b = 3
vector_v = np.array([1, 2])

result1 = (scalar_a * scalar_b) * vector_v
result2 =  scalar_a * (scalar_b * vector_v)

print("Result using (a * b) * v:", result1)
print("Result using a * (b * v):", result2)

Result using (a * b) * v: [ 6 12]
Result using a * (b * v): [ 6 12]


##### Commutative Property of Dot Product:
The dot product of two vectors is commutative, meaning that the order of vectors in the product doesn't affect the result.

u⋅v=v⋅u

In [23]:
vector_u = np.array([1, 2, 3])
vector_v = np.array([4, 5, 6])

result1 = np.dot(vector_u, vector_v)
result2 = np.dot(vector_v, vector_u)

print("Result using u dot v:", result1)
print("Result using v dot u:", result2)

Result using u dot v: 32
Result using v dot u: 32


##### Distributive Property of Dot Product over Vector Addition:
The dot product distributes over vector addition, meaning that the dot product of a vector sum is the same as the sum of the dot products of the individual vectors.


u⋅(v+w)=u⋅v+u⋅w

In [24]:
vector_u = np.array([1, 2])
vector_v = np.array([3, 4])
vector_w = np.array([5, 6])

result1 = np.dot(vector_u, vector_v + vector_w)
result2 = np.dot(vector_u, vector_v) + np.dot(vector_u, vector_w)

print("Result using u dot (v + w):", result1)
print("Result using u dot v + u dot w:", result2)

Result using u dot (v + w): 28
Result using u dot v + u dot w: 28
