In [1]:
from IPython.display import Image

In [2]:
import numpy as np

---------------------------
#### Mathematical functions
--------------------

##### Rounding
|Function name | What it does?|
|--------------|--------------|
|around(a[, decimals, out]) |Evenly round to the given number of decimals.|
|round_(a[, decimals, out]) |Round an array to the given number of decimals.|
|rint(x, /[, out, where, casting, order, …])|Round elements of the array to the nearest integer.|
|fix(x[, out])| Round to nearest integer towards zero.|
|floor(x, /[, out, where, casting, order, …])| Return the floor of the input, element-wise.|
|ceil(x, /[, out, where, casting, order, …])|Return the ceiling of the input, element-wise.|
|trunc(x, /[, out, where, casting, order, …])|Return the truncated value of the input, element-wise.|



`around/ round` 

- Numpy around() is a mathematical function that helps the user to `evenly round array elements to the given number of decimals`. 

- The around() method takes up to three parameters and returns an array with all the elements being rounded off to the specified value.

In [87]:
np.around([0.37, 1.64]), np.round([0.37, 1.64])

(array([0., 2.]), array([0., 2.]))

In [88]:
np.around([0.33, 0.37, 1.64, 1.66], decimals=1), np.round([0.33, 0.37, 1.64, 1.66], decimals=1)

(array([0.3, 0.4, 1.6, 1.7]), array([0.3, 0.4, 1.6, 1.7]))

In [89]:
np.around([.5, 1.5, 2.5, 3.5, 4.5, 4.7]) , np.round([.5, 1.5, 2.5, 3.5, 4.5, 4.7]) 

(array([0., 2., 2., 4., 4., 5.]), array([0., 2., 2., 4., 4., 5.]))

> both round/around are same functions

`numpy.rint`

- Round elements of the array to the nearest integer.

In [91]:
np.rint([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])

array([-2., -2., -0.,  0.,  2.,  2.,  2.])

`numpy.fix`

- Round an array of floats element-wise to nearest integer towards zero. The rounded values are returned as floats.

In [95]:
np.fix([3.14, 3.7]), np.rint([3.14, 3.7])

(array([3., 3.]), array([3., 4.]))

In [96]:
np.fix([2.1, 2.9, -2.1, -2.9]), np.rint([2.1, 2.9, -2.1, -2.9])

(array([ 2.,  2., -2., -2.]), array([ 2.,  3., -2., -3.]))

`numpy.floor`

- Return the floor of the input, element-wise.

- The floor of the scalar x is the largest integer i, such that i <= x. It is often denoted as $\large \lfloor x \rfloor$.

In [98]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.1, 1.5, 1.7, 2.0])
np.floor(a)

array([-2., -2., -1.,  0.,  1.,  1.,  1.,  2.])

`numpy.ceil`

- Return the `ceiling` of the input, element-wise.

- The ceil of the scalar x is the smallest integer i, such that i >= x. It is often denoted as $\lceil x \rceil$.

In [99]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.ceil(a)

array([-1., -1., -0.,  1.,  2.,  2.,  2.])

`numpy.trunc`

- Return the `truncated` value of the input, element-wise.

- The truncated value of the scalar x is the nearest integer i which is closer to zero than x is. In short, the `fractional part of the signed number x is discarded`.

In [100]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.trunc(a)

array([-1., -1., -0.,  0.,  1.,  1.,  2.])