In [2]:
from IPython.display import Image

--------------
#### Set routines
-----------------------

A `set` is a collection of `unique values` on which we can perform various operations. 

The operation which we usually perform on sets is 
- union, 
- intersection and 
- difference operations. 

These operations help us in data manipulation and then this data we can use anywhere.

##### Creating Sets
- In NumPy, we have a method with the help of which we can create a set that will help us in finding `unique values`. 

- This method is `unique()`. 

- When we are creating the set array, it should always be in one dimension only.

In [1]:
import numpy as np

In [2]:
my_arr = np.array([1,2,3,1,1,2,3,3,4,5,5,4,1,2,3])

my_arr_set = np.unique(my_arr)

print(my_arr_set)

[1 2 3 4 5]


##### Finding Union

- we use the `union1d()` method. we will be able to combine all the values of the two arrays we have given which are unique.

In [3]:
a=np.array([9,8,7,6,6])
b=np.array([6,5,4,3])

In [4]:
np.union1d(a,b)

array([3, 4, 5, 6, 7, 8, 9])

##### Finding Intersection

- When we want to find `only common values` that present in both the array, we use the `intersection` method. 

- we use `intersect1d()` method.

In [5]:
a=np.array([9,3,7,6,6])
b=np.array([6,5,4,3])

c=np.intersect1d(a,b,assume_unique=True)

print(c)

[3 6 6]


##### Finding Difference

- In order to find the difference between the two sets, we use `setdiff1d()` the method. 

- In this, we will get value in the first set that is not present in the second set.

In [6]:
a=np.array([9,3,7,6,6])
b=np.array([6,5,4,3])
 
c=np.setdiff1d(a,b,assume_unique=True)

print(c)

[9 7]


----------------------
#### similarity between Sets - Using Jaccard Similarity
---------------

- The `Jaccard index`, also known as the `Jaccard similarity coefficient`, is a statistic used for gauging the `similarity` and `diversity` of sample sets. 

- It was developed by `Paul Jaccard`, originally giving the French name coefficient de communauté, and independently formulated again by T. Tanimoto. 

- The Jaccard coefficient measures similarity between finite sample sets, and is defined as the size of the intersection divided by the size of the union of the sample sets:

$$ \large J(A,B) = \frac{\left|A \cap B\right|}{\left|A \cup B\right|}$$

$$0 \le J(A,B) \le 1$$

In [15]:
def jaccard(s1, s2):
    " takes two lists as input and returns Jaccard coefficient"
    st1=set(s1)
    st2=set(s2)
    
    u = np.union1d(s1 ,s2)
    
    i = np.intersect1d(s1, s2)
#     u = set(st1).union(st2)
#     i = set(st1).intersection(st2)
    
    return len(i)/len(u)

In [16]:
s = [];
s.append([1,2,3,4])
s.append([2,3,5,7])
s.append([2,4,6])  
s.append([8,9,10,11,12])

print("input set : ", s)

input set :  [[1, 2, 3, 4], [2, 3, 5, 7], [2, 4, 6], [8, 9, 10, 11, 12]]


In [17]:
import itertools

In [18]:
combinations = list( itertools.combinations([x for x in range(len(s))], 2) )
combinations

[(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]

In [24]:
for c in combinations:
        i1 = c[0]
        i2 = c[1]
        
        jac = jaccard(s[i1], s[i2])
        
        print("{} -> {} {} : jaccard= {:f}".format(c, s[i1], s[i2], jac))

(0, 1) -> [1, 2, 3, 4] [2, 3, 5, 7] : jaccard= 0.333333
(0, 2) -> [1, 2, 3, 4] [2, 4, 6] : jaccard= 0.400000
(0, 3) -> [1, 2, 3, 4] [8, 9, 10, 11, 12] : jaccard= 0.000000
(1, 2) -> [2, 3, 5, 7] [2, 4, 6] : jaccard= 0.166667
(1, 3) -> [2, 3, 5, 7] [8, 9, 10, 11, 12] : jaccard= 0.000000
(2, 3) -> [2, 4, 6] [8, 9, 10, 11, 12] : jaccard= 0.000000


----------------
#### w-shingling - for checking plagiarism
-----------------

- "Suppose our document D is the string "abcdabd", and we pick k= 2. Then the set of 2-shingles for D is {ab,bc,cd,da,bd}. Note that the substring "ab" appears twice within D, but appears only once as a shingle."

- We will use 3 documents, 
    - the first one is the original 
    - but the second one is the plagiarized the first one. 
    - The third one is an unrelated doc. 

- When we look at the result (Jaccard coefficient), clearly doc[0] and doc[1] are similar:

In [25]:
import itertools

def jaccard_set(s1, s2):
    " takes two lists as input and returns Jaccard coefficient"
    st1=set(s1)
    st2=set(s2)
    
    u = np.union1d(s1 ,s2)
    i = np.intersect1d(s1, s2)
    
#     u = set(st1).union(st2)
#     i = set(st1).intersection(st2)
    
    return len(i)/len(u)

In [26]:
documents = ["The legal system is made up of civil courts, criminal courts and specialty courts such as family law courts and bankruptcy court. Each court has its own jurisdiction, which refers to the cases that the court is allowed to hear. In some instances, a case can only be heard in one type of court. For example, a bankruptcy case must be heard in a bankruptcy court. In other instances, there may be several potential courts with jurisdiction. For example, a federal criminal court and a state criminal court would each have jurisdiction over a crime that is a federal drug offense but that is also an offense on the state level.",
      "The legal system is comprised of criminal and civil courts and specialty courts like bankruptcy and family law courts. Every one of the courts is vested with its own jurisdiction. Jurisdiction means the types of cases each court is permitted to rule on. Sometimes, only one type of court can hear a particular case. For instance, bankruptcy cases an be ruled on only in bankruptcy court. In other situations, it is possible for more than one court to have jurisdiction. For instance, both a state and federal criminal court could have authority over a criminal case that is illegal under federal and state drug laws.",
      "In many jurisdictions the judicial branch has the power to change laws through the process of judicial review. Courts with judicial review power may annul the laws and rules of the state when it finds them incompatible with a higher norm, such as primary legislation, the provisions of the constitution or international law. Judges constitute a critical force for interpretation and implementation of a constitution, thus de facto in common law countries creating the body of constitutional law."]

In [27]:
# shingle size
k = 9

In [29]:
shingles = []

for doc in documents:
    sh   = set()
    size = len(doc)
    
    for i in range(size-k):
        sh.add(doc[i:i+k])
        
    print("size= {} {}".format(len(sh), sh))
    shingles.append(sh)

size= 542 {'r. In som', 'y courts ', 'urt. For ', ' case mus', 'law court', ' is allow', 'tential c', 'h have ju', 'potential', 'ourt. Eac', 'such as f', 'rime that', ' example,', ' which re', ' is also ', ' also an ', 'is a fede', 'ense but ', 'ral crimi', 'is allowe', 'the cases', 'he cases ', 'ses that ', 'crime tha', 'vil court', 's allowed', 'own juris', 'deral cri', 's, crimin', 'have juri', ' crime th', 'would eac', ' is made ', 'l court w', ' courts w', 'tion. For', 'type of c', ' state cr', ' In other', 'ial court', 'ard in on', 'cy court.', 'o hear. I', 'with juri', ' bankrupt', 'rt. For e', 'In other ', 'example, ', 'h as fami', 'o the cas', 'h refers ', 'system is', 'e, a bank', 'mily law ', 't. For ex', 'ourts wit', 'stances, ', ' offense ', 'ch court ', 'one type ', ' case can', 't would e', 'her insta', 'risdictio', 'e up of c', 'al system', ' must be ', ' instance', ' to hear.', 'ourt is a', 'minal cou', 'd in one ', 'ample, a ', 'd in a ba', 'a crime t', 'f court. ', '

In [31]:
combinations = list( itertools.combinations([x for x in range(len(shingles))], 2) )

print("combinations=s",combinations)

combinations=s [(0, 1), (0, 2), (1, 2)]


In [ ]:
# combinations of shingles(=numbe of docs)
    for c in combinations:
        i1 = c[0]
        i2 = c[1]
        jac = jaccard_set(shingles[i1], shingles[i2])
        print("%s : jaccard=%s") %(c,jac)

In [32]:
for c in combinations:
        i1 = c[0]
        i2 = c[1]
        
        jac = jaccard(s[i1], s[i2])
        
        print("{} -> {} {} : jaccard= {:f}".format(c, s[i1], s[i2], jac))

(0, 1) -> [1, 2, 3, 4] [2, 3, 5, 7] : jaccard= 0.333333
(0, 2) -> [1, 2, 3, 4] [2, 4, 6] : jaccard= 0.400000
(1, 2) -> [2, 3, 5, 7] [2, 4, 6] : jaccard= 0.166667


Selecting appropriate k is not easy. If we use k=5 instead of k=9, we get different result:

we can see the `last document is not similar to the first two docs` while the `first` and the `second` one appear to have some `similarities`.