In [1]:
import numpy as np

... small talk on `np.argmax` ...


- only returns the first occurance of the max value (returns index)

In [2]:
arr = np.random.randint(low=5, high=15, size=6)
print(arr)

np.argmax(arr)

[ 7  8  7 11  6  7]


3

In [9]:
arr = np.random.randint(low=5, high=15, size=6).reshape(2, 3)
print(arr)

np.argmax(arr)

[[10 13  9]
 [ 6  6 13]]


1

In [10]:
arr = np.random.randint(low=5, high=15, size=6).reshape(2, 3)
print(arr)

np.argmax(arr, axis=0)

[[ 9  6  5]
 [13  9 11]]


array([1, 1, 1], dtype=int64)

In [11]:
arr = np.random.randint(low=5, high=15, size=6).reshape(2, 3)
print(arr)

np.argmax(arr, axis=1)

[[ 8  9 10]
 [ 5 12  8]]


array([2, 1], dtype=int64)

... small talk on `np.where` ...

In [12]:
arr = np.arange(12)
print(arr)

np.where(arr < 5)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


(array([0, 1, 2, 3, 4], dtype=int64),)

In [13]:
arr = np.random.randint(low=5, high=15, size=6)
print(arr)

np.where(arr < 10)

[10 13  7 14 12  5]


(array([2, 5], dtype=int64),)

In [14]:
arr = np.random.randint(low=5, high=15, size=(3, 3))
print(arr)

np.where(arr < 10)

[[ 9  5 10]
 [ 6  8 10]
 [11 11 12]]


(array([0, 0, 1, 1], dtype=int64), array([0, 1, 0, 1], dtype=int64))

In [15]:
arr = np.arange(12).reshape(1, 12)
print(arr)

np.where(arr < 5)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]]


(array([0, 0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3, 4], dtype=int64))

In [16]:
arr = np.arange(12).reshape(3, 4)
print(arr)

np.where(arr < 5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


(array([0, 0, 0, 0, 1], dtype=int64), array([0, 1, 2, 3, 0], dtype=int64))

how do get `multiple (all) indices` where the maximum value is stored in the array 

In [17]:
arr = [7, 6, 5, 7, 6, 7, 6, 6, 6, 4, 5, 6]

print(np.argmax(arr))

winner = np.where(arr == np.max(arr))

print(winner)

0
(array([0, 3, 5], dtype=int64),)


In [18]:
np.where(arr == np.max(arr))[0]

array([0, 3, 5], dtype=int64)