In [2]:
from IPython.display import Image

In [3]:
import numpy as np

---------------------------
#### Mathematical functions
--------------------

##### Arithmetic operations

|Function | What it does |
|---------|--------------|
|add(x1, x2, /[, out, where, casting, order, …])|Add arguments element-wise.|
|reciprocal(x, /[, out, where, casting, …])|Return the reciprocal of the argument, element-wise.|
|positive(x, /[, out, where, casting, order, …])|Numerical positive, element-wise.|
|negative(x, /[, out, where, casting, order, …])|Numerical negative, element-wise.|
|multiply(x1, x2, /[, out, where, casting, …])|Multiply arguments element-wise.|
|divide(x1, x2, /[, out, where, casting, …])|Returns a true division of the inputs, element-wise.|
|power(x1, x2, /[, out, where, casting, …])|First array elements raised to powers from second array, element-wise.|
|subtract(x1, x2, /[, out, where, casting, …])|Subtract arguments, element-wise.|
|true_divide(x1, x2, /[, out, where, …])|Returns a true division of the inputs, element-wise.|
|floor_divide(x1, x2, /[, out, where, …])|Return the largest integer smaller or equal to the division of the inputs.|
|float_power(x1, x2, /[, out, where, …])|First array elements raised to powers from second array, element-wise.|
|fmod(x1, x2, /[, out, where, casting, …])|Return the element-wise remainder of division.|
|mod(x1, x2, /[, out, where, casting, order, …])|Return element-wise remainder of division.|
|modf(x[, out1, out2], / [[, out, where, …])| Return the fractional and integral parts of an array, element-wise.|
|remainder(x1, x2, /[, out, where, casting, …])| Return element-wise remainder of division.|
|divmod(x1, x2[, out1, out2], / [[, out, …]) |Return element-wise quotient and remainder simultaneously.|

`numpy.add`

Add arguments element-wise.



In [4]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)

x1, x2


(array([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]),
 array([0., 1., 2.]))

In [5]:
np.add(x1, x2)

array([[ 0.,  2.,  4.],
       [ 3.,  5.,  7.],
       [ 6.,  8., 10.]])

`numpy.reciprocal`

- Return the reciprocal of the argument, element-wise.

- Calculates 1/x.

In [7]:
np.reciprocal([1, 2., 3.33])

array([1.       , 0.5      , 0.3003003])

`numpy.positive` and `numpy.negative`

- Numerical positive, element-wise.

In [9]:
np.positive([-10, -20, 30])

array([-10, -20,  30])

In [11]:
in_arr = np.array([[2, -7, 5], [-6, 2, 0]]) 
in_arr 

array([[ 2, -7,  5],
       [-6,  2,  0]])

In [12]:
out_arr = np.negative(in_arr)  
out_arr

array([[-2,  7, -5],
       [ 6, -2,  0]])

`numpy.multiply`

- Multiply arguments element-wise.

In [14]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
x1, x2


(array([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]),
 array([0., 1., 2.]))

In [15]:
np.multiply(x1, x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

`numpy.divide`

- Returns a true division of the inputs, element-wise.

In [16]:
x = np.arange(5)
np.true_divide(x, 4)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

`numpy.power`

- First array elements raised to powers from second array, element-wise.

In [18]:
x1 = range(6)
x1

range(0, 6)

In [19]:
np.power(x1, 3)

array([  0,   1,   8,  27,  64, 125], dtype=int32)

Raise the bases to different exponents.

In [20]:
x1 = range(6)
x2 = [1.0, 2.0, 3.0, 3.0, 2.0, 1.0]

In [21]:
np.power(x1, x2)

array([ 0.,  1.,  8., 27., 16.,  5.])

The effect of broadcasting.

In [22]:
x1 = range(6)
x2 = np.array([[1, 2, 3, 3, 2, 1], [1, 2, 3, 3, 2, 1]])

In [23]:
np.power(x1, x2)

array([[ 0,  1,  8, 27, 16,  5],
       [ 0,  1,  8, 27, 16,  5]], dtype=int32)

`numpy.mod`

- Return element-wise remainder of division.

In [24]:
np.remainder([4, 7], [2, 3])

array([0, 1], dtype=int32)

In [25]:
np.remainder(np.arange(7), 5)

array([0, 1, 2, 3, 4, 0, 1], dtype=int32)