In [1]:
from IPython.display import Image

In [2]:
import numpy as np

---------------------------
#### Mathematical functions
--------------------

##### Sums, products, differences


| Functions | what does it do? |
|-----------|------------------|
|prod(a[, axis, dtype, out, keepdims, …]) | Return the product of array elements over a given axis.|
|sum(a[, axis, dtype, out, keepdims, …])|Sum of array elements over a given axis.|
|nanprod(a[, axis, dtype, out, keepdims])|Return the product of array elements over a given axis treating Not a Numbers (NaNs) as ones.|
|nansum(a[, axis, dtype, out, keepdims])|Return the sum of array elements over a given axis treating Not a Numbers (NaNs) as zero.|
|cumprod(a[, axis, dtype, out])|Return the cumulative product of elements along a given axis.|
|cumsum(a[, axis, dtype, out])|Return the cumulative sum of the elements along a given axis.|
|nancumprod(a[, axis, dtype, out])|Return the cumulative product of array elements over a given axis treating Not a Numbers (NaNs) as one.|
|nancumsum(a[, axis, dtype, out])|Return the cumulative sum of array elements over a given axis treating Not a Numbers (NaNs) as zero.|
|diff(a[, n, axis, prepend, append])|Calculate the n-th discrete difference along the given axis.|
|ediff1d(ary[, to_end, to_begin])|The differences between consecutive elements of an array.|
|gradient(f, \*varargs[, axis, edge_order])|Return the gradient of an N-dimensional array.|
|cross(a, b[, axisa, axisb, axisc, axis])|Return the cross product of two (arrays of) vectors.|
|trapz(y[, x, dx, axis])|Integrate along the given axis using the composite trapezoidal rule.|

`numpy.prod`

- Return the product of array elements over a given axis.

In [102]:
x = np.array([536870910, 536870910, 536870910, 536870910])
np.prod(x)

16

The product of an empty array is the neutral element 1:


In [106]:
np.prod([])

1.0

In [107]:
np.prod([[],[]])

1.0

In [108]:
np.prod([[1.,2.],[3.,4.]])

24.0

In [109]:
np.prod([[1.,2.],[3.,4.], [10, 20]])

4800.0

we can also specify the axis over which to multiply:

In [117]:
np.prod([[1., 2.],
         [3., 4.]], axis=1)   # row wise

array([ 2., 12.])

In [118]:
np.prod([[1., 2.],
         [3., 4.]], axis=0)   # column wise

array([3., 8.])

You can also start the product with a value other than one:

In [111]:
np.prod([1, 2], initial=5)

10

`numpy.sum`
- Sum of array elements over a given axis.

In [112]:
np.sum([])

0.0

In [113]:
np.sum([0.5, 1.5])

2.0

In [114]:
np.sum([[0, 1], 
        [0, 5]])

6

In [115]:
np.sum([[0, 1], [0, 5]], keepdims=True)

array([[6]])

In [116]:
np.sum([[0, 1], 
        [0, 5]], axis=0)   # column wise

array([0, 6])

In [119]:
np.sum([[0, 1], 
        [0, 5]], axis=1)   # row wise

array([1, 5])

`numpy.nanprod`

- Return the product of array elements over a given axis treating Not a Numbers (NaNs) as ones.

- 1 is returned for slices that are all-NaN or empty.

In [120]:
np.nanprod(1)

1

In [121]:
np.nanprod([1]), np.nanprod([])

(1, 1.0)

In [122]:
np.nanprod([10, np.nan])

10.0

In [123]:
a = np.array([[1, 2], 
              [3, np.nan]])

np.nanprod(a)

6.0

In [124]:
np.nanprod(a, axis=0)    # Column wise

array([3., 2.])

In [125]:
np.nanprod(a, axis=1)    # Row wise

array([2., 3.])

`numpy.nansum`

- Return the sum of array elements over a given axis treating `Not a Numbers` (NaNs) as `zero`.


In [126]:
np.nansum(1)

1

In [127]:
np.nansum([1])

1

In [128]:
np.nansum([1, np.nan])

1.0

In [132]:
a = np.array([[1, 5], 
              [1, np.nan]])

In [133]:
np.nansum(a, axis=0)    # column wise

array([2., 5.])

In [134]:
np.nansum(a, axis=1)    # row wise

array([6., 1.])

In [135]:
np.nansum([1, np.nan, np.inf])

inf

In [136]:
np.nansum([1, np.nan, np.NINF])

-inf

`numpy.cumprod`

- Return the cumulative product of elements along a given axis.

In [141]:
a = np.array([1,2,3])
np.cumprod(a)

array([1, 2, 6], dtype=int32)

In [148]:
a = np.array([[1, 2, 3], 
              [4, 5, 6],
              [7, 8, 9]
             ])

np.cumprod(a, dtype=int)

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880], dtype=int32)

In [149]:
np.cumprod(a, axis=0)

array([[  1,   2,   3],
       [  4,  10,  18],
       [ 28,  80, 162]], dtype=int32)

In [150]:
np.cumprod(a, axis=1)

array([[  1,   2,   6],
       [  4,  20, 120],
       [  7,  56, 504]], dtype=int32)

`numpy.nancumprod`

- Return the `cumulative` product of array elements over a given axis treating Not a Numbers (NaNs) as 1. 
- The cumulative product does not change when NaNs are encountered and leading NaNs are replaced by ones.

Ones are returned for slices that are all-NaN or empty.

In [152]:
a = np.array([[1, 2], 
              [3, np.nan]])

In [153]:
np.nancumprod(a)

array([1., 2., 6., 6.])

In [154]:
np.nancumprod(a, axis=0)

array([[1., 2.],
       [3., 2.]])

In [155]:
np.nancumprod(a, axis=1)

array([[1., 2.],
       [3., 3.]])

`numpy.nancumsum`
- Return the cumulative sum of array elements over a given axis treating Not a Numbers (NaNs) as zero. 
- The cumulative sum does not change when NaNs are encountered and leading NaNs are replaced by zeros.

Zeros are returned for slices that are all-NaN or empty.

In [156]:
a = np.array([[1, 2], 
              [3, np.nan]])

In [157]:
np.nancumsum(a)

array([1., 3., 6., 6.])

In [158]:
np.nancumsum(a, axis=0)

array([[1., 2.],
       [4., 2.]])

In [159]:
np.nancumsum(a, axis=1)

array([[1., 3.],
       [3., 3.]])

`numpy.diff`

- Calculate the n-th discrete difference along the given axis.

- The first difference is given by out[i] = a[i+1] - a[i] along the given axis, higher differences are calculated by using diff recursively.

- Parameters
    - `a` array_like Input array
    - `n` int, optional
        - The number of times values are differenced. 
            - If zero, the input is returned as-is.

In [160]:
x = np.array([1, 2, 4, 7, 0])
np.diff(x)

array([ 1,  2,  3, -7])

In [161]:
np.diff(x, n=2)

array([  1,   1, -10])

In [162]:
x = np.array([[1, 3, 6, 10], 
              [0, 5, 6, 8]])

In [163]:
np.diff(x)

array([[2, 3, 4],
       [5, 1, 2]])

In [164]:
np.diff(x, axis=0)

array([[-1,  2,  0, -2]])

In [165]:
np.diff(x, axis=1)

array([[2, 3, 4],
       [5, 1, 2]])